### PR TITLE
[Issue 16] Add Grype for vulnerability scanning

### LINKED ISSUE #16: Add grype for container scanning
Like [`template-application-nextjs`](https://github.com/navapbc/template-application-nextjs), add [grype](https://github.com/anchore/grype) for container scanning.

### PR DESCRIPTION
**Pull request by SammySteiner**
## Ticket

- Resolves #16 

## Changes

- Added .grype.yml file to root directory
- Added .grype.yml to the template-only-bin/install-template.sh file to transfer the .grype.yml file to repos created with the template

## Context for reviewers

Tested by running grype locally on database image and application image with and without the .grype.yml file to make sure it was loading and formatted correctly. 

## Testing

Install and run Grype locally with and without the .grype.yml file ignore to confirm it is working as intended.

### CODE REVIEW

**Comment by ellery-nava** [comment]
Do we need to update the README with any instructions on installing and running Grype? 
Should it be run automatically on PRs? Or are we expecting developers to run manually?

**Comment by SammySteiner** [comment]
> Do we need to update the README with any instructions on installing and running Grype?
> Should it be run automatically on PRs? Or are we expecting developers to run manually?

I haven't been on a project where developers were running it manually, unless there was a vulnerability identified by the scan. At which point, you can run it locally, but I think most people were relying on the ci pipeline to run when push changes to the PR.

**Comment by ellery-nava** [comment]
Makes sense - is  this adding to the CI workflows part of this ticket? Not familiar with how much comes out of the box usually on Platform projects

**Comment by SammySteiner** [comment]
> Makes sense - is this adding to the CI workflows part of this ticket? Not familiar with how much comes out of the box usually on Platform projects

The ticket referenced the [template-nextjs](https://github.com/navapbc/template-application-nextjs) repo's implementation, which only contains the bin script update and the .grype.yml file, it's assuming the [ci workflow](https://github.com/navapbc/template-infra/blob/main/.github/workflows/vulnerability-scans.yml) is coming from the infra repo. So I decided to use that implementation as my guide for how far to take it.

**Review by ellery-nava — APPROVED** [review]
Thanks for all the clarification! Approved

**Review by rocketnova — COMMENTED** [review]
LGTM. Thank you!

**Pull request merged**
